use Ankita12;


CREATE TABLE EMP(
ID INT PRIMARY KEY IDENTITY,
NAME VARCHAR(50),
CITY VARCHAR(100),
DEPARTMENT VARCHAR(60),
SALARY INT NOT NULL
);


insert into EMP VALUES('AMAN','BEGUSARAI', 'ENGINEERING', 50000),
						  ('RADHA','BARAUNI','FINANCE', 60000),
						  ('PINKI','LKO', 'HR', 60000),
						  ('SIKHA','HAJIPUR', 'MARKETING', 50000),
						  ('KOMAL','FAIZABAD', 'FINANCE', 70000),
						  ('PAYAL', 'GORAKHPUR', 'ENGINEERING', 80000),
						  ('AMAN','BEGUSARAI', 'ENGINEERING', 50000);
SELECT * FROM EMP;


-- Find salaries that occur more than once.
SELECT SALARY, COUNT(*) AS EMP_SALARY FROM EMP 
GROUP BY SALARY HAVING COUNT(*) >1;



-- the actual employees having duplicate salaries.
SELECT * from EMP WHERE SALARY IN(
SELECT SALARY FROM EMP GROUP BY SALARY 
HAVING COUNT(*) >1
);


-- Find duplicate records.
WITH DuplicateRecords AS
(
SELECT ID, NAME, CITY, DEPARTMENT, SALARY, ROW_NUMBER()
OVER(PARTITION BY NAME, CITY, DEPARTMENT, SALARY
ORDER BY ID) AS DUP_RECORD FROM EMP 
)

SELECT * FROM DuplicateRecords
WHERE DUP_RECORD > 1;



-- DELETE the duplicate records
WITH DuplicateRecords AS
(
SELECT ID, NAME, CITY, DEPARTMENT, SALARY, ROW_NUMBER()
OVER(PARTITION BY NAME, CITY, DEPARTMENT, SALARY
ORDER BY ID) AS DUP_RECORD FROM EMP 
)

DELETE FROM DuplicateRecords
WHERE DUP_RECORD > 1;

-- find 2nd highest salary

SELECT ID, NAME, CITY FROM EMP 
ORDER BY SALARY DESC
OFFSET 1 ROWS
FETCH NEXT 1 ROW ONLY;


--2 METHOD
SELECT * FROM EMP WHERE SALARY= (

SELECT MAX(SALARY) FROM EMP WHERE SALARY <
(SELECT MAX (SALARY) FROM EMP)
)

-- 3 METHOD
WITH CTE AS (
SELECT ID, NAME, CITY, DEPARTMENT, SALARY,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RNK
FROM EMP
)
SELECT * FROM CTE
WHERE RNK = 3;


-- find Nth highest salary

WITH CTE AS (
SELECT ID, NAME, CITY, DEPARTMENT, SALARY,
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RNK
FROM EMP
)
SELECT * FROM CTE
WHERE RNK = 4;


-- ------

select distinct salary from EMP 
order by SALARY desc
offset 2 rows
fetch next 1 row only;



-- find highest salary by department
WITH CTE AS (
SELECT *, RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC)
AS RNK FROM EMP 
)

SELECT *
FROM CTE
WHERE RNK = 1;


-- Find employees above average salary

SELECT * FROM EMP WHERE SALARY 
 > (SELECT AVG(SALARY) FROM EMP);


 -- find employees without managers.

-- Find departments with 1+ employees.

SELECT DEPARTMENT, COUNT(*) AS EMP_COUNT
FROM EMP GROUP BY DEPARTMENT 
HAVING COUNT(*) > 1;


-- RANK vs DENSE_RANK vs ROW_NUMBER
SELECT
    NAME,
    SALARY,

    ROW_NUMBER() OVER
    (
        ORDER BY SALARY DESC
    ) AS ROW_NUM,

    RANK() OVER
    (
        ORDER BY SALARY DESC
    ) AS RNK,

    DENSE_RANK() OVER
    (
        ORDER BY SALARY DESC
    ) AS DENSE_RNK

FROM EMP;


-- FIND TOP 3 SALARIES PER DEPARTMENT
WITH CTE AS (
SELECT *, DENSE_RANK() OVER
(PARTITION BY DEPARTMENT ORDER BY SALARY DESC)
AS RNK FROM EMP)

SELECT * FROM CTE 
WHERE RNK <=3;


-- FIND HIGHEST PAID EMPLOYEE PER DERPATMENT

WITH CTE AS
(
    SELECT
        *,
        RANK() OVER
        (
            PARTITION BY DEPARTMENT
            ORDER BY SALARY DESC
        ) AS RNK
    FROM EMP
)
SELECT *
FROM CTE
WHERE RNK = 1;